Name.Csの原型を作成(#104)
traPortation/traPortation-mini pull request #106
Opened 2021-11-13 09:30 UTC by AliceSignal

・Name.CsはInputFieldオブジェクトにアタッチしている
・入力が確定した文字は静的変数resultNameに格納されて、他関数で取り出すことが可能
・serializedVersionとか変わってるの大丈夫ですか...?

2021-11-13 09:36 UTC, AliceSignal commented
このプルリクエストをマージするとissue(#104)も閉じるので、新しく関数の改善点があったら新しくissueを立てます

2021-11-15 10:46 UTC, reyu0722 commented
↑ `Name.cs` だけ文字コードが他と違っていたので揃えました

2021-11-15 16:34 UTC, reyu0722 requested changes

2021-11-15 16:34 UTC, reyu0722 commented on Assets/Scripts/Name.cs
> +    public static string resultName;  // 入力されたテキスト
多分クラスの外部から書き換えることはないと思うので、 `{ get; private set; }` をつけるといい感じになりそうです

2021-11-15 16:34 UTC, reyu0722 commented on Assets/Scripts/Name.cs
> +    public static string resultName;  // 入力されたテキスト
プロパティとかメソッドの説明のコメントは

```csharp
/// <summary>
/// 入力されたテキスト
/// </summary>
public static string resultName;
```

みたいな感じ (多分 `///` を打つといい感じに出てくる) に書くとエディタ上のマウスホバーとかで出てくるようになるので、そうするとよさそうです

2021-11-15 16:34 UTC, reyu0722 commented on Assets/Scripts/Board/RailManager.cs
>          int index = this.rails[this.rails.Count].Index;
```suggestion
        int index = this.rails[this.rails.Count - 1].Index + 1;
```

が正しそうです

2021-11-15 16:34 UTC, reyu0722 commented on Assets/Scripts/Board/RailManager.cs
>          int index = this.rails[this.rails.Count].Index;
そもそも `Rail.Index` より `Rail.ID` とかのほうが適切な気がしてきました
(今読んでて `this.rails.Count` は `index` にならないのか？と一瞬なって混乱したので)

2021-11-15 16:34 UTC, reyu0722 commented on Assets/Scripts/Board/RailManager.cs
> +    public void ChangeRailName(Rail rail)
進捗会のときには違うことを言った気もするんですが (最悪)、今考えるとこの機能は `Rail` にあったほうがよさそうです (そのほうが役割的にも正しそうだし `Rail.Name` のsetterをprivateにできてよかったりするので)

そうすると例えばRail間での名前被りを防止したいってなったときに困るんですが、よく考えると `RailManager` をSingletonにすると解決できるので大丈夫そうです (SingletonはBoardとかで使ってるやつで、詳しくは~~書くのは大変なので~~調べてみてください)

2021-11-17 07:30 UTC, AliceSignal commented on Assets/Scripts/Name.cs
> +public class Name : MonoBehaviour
inputNameにしました。

2021-11-17 07:53 UTC, AliceSignal commented on Assets/Scripts/Board/RailManager.cs
> +    public void ChangeRailName(Rail rail)
多分できました

2021-11-17 08:35 UTC, AliceSignal commented on Assets/Scripts/Name.cs
> +    public void FinishEditName()
これ明日の集会で詳しく聞きたいです

2021-11-18 12:39 UTC, AliceSignal commented on Assets/Scripts/Name.cs
> +    public void FinishEditName()
解決しました

2021-11-18 12:43 UTC, reyu0722 commented
:LGTM:

2021-11-18 12:44 UTC, merged