プルリク#115のつづき
traPortation/traPortation-mini pull request #117
Opened 2021-11-25 12:37 UTC by AliceSignal

#115 参照
メインカメラが動くようになった
スワイプ操作とマウスドラッグが互換性を持つようになる
・↑に対してのチェンジリクエストと少し解決　←いまここ

2021-11-25 12:38 UTC, AliceSignal commented
こちらがマージされたのを確認したら#115も(手動で)閉じます

2021-11-25 12:43 UTC, AliceSignal commented
またcodecovくん何か言ってる...

2021-12-20 09:32 UTC, reyu0722 requested changes
引き続き参考元への指摘が多めです

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/TouchManager.cs
> +        public bool touchFlag;      // タッチ有無
ここも上と同じように `isTouching` とかのほうがわかりやすそうです

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/TouchManager.cs
> +        public TouchPhase touchPhase;   // タッチ状態
全部publicでget/setできるのはよくないので、必要ないところはprivateとかにしといてください

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/TouchManager.cs
> +        public TouchManager(bool flag = false, Vector2? position = null, TouchPhase phase = TouchPhase.Began)
```suggestion
        public TouchManager()
```

引数が必要な場面がぱっと思いつかないので、なくしていい気がします
ちゃんと考えてないのでそうでもないかもしれない

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/CameraMove.cs
> +    private Vector2 touchPosition_cam;
変数名があまり適切ではない気がします

`Camera.ScreenToWorldPoint` はスクリーンでの座標をワールドの座標に変換するもの (らしい) ので、`touchPositionInWorld` にするか、そもそも `touchPosition` にしちゃってもいいかもしれません (`scrollStartPos` もワールドの座標なので)

https://docs.unity3d.com/jp/current/ScriptReference/Camera.ScreenToWorldPoint.html

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/CameraMove.cs
> +                    Vector2 touchMovePos = touchPosition_cam;
ここで再代入する意味はない気がします

2021-12-20 09:32 UTC, reyu0722 commented on Assets/Scripts/TouchManager.cs
> +        public void update()
毎回勝手に呼ばれるわけではないので、`Update is called once per frame` は誤解を生みそうです
`Update should be called once per frame` にするといいかもしれないです

2022-12-09 10:50 UTC, closed without merging