Fix person move
traPortation/traPortation-mini pull request #118
Opened 2021-12-01 19:25 UTC by dora1500

2021-12-16 09:14 UTC, reyu0722 requested changes
余裕がありそうだったらテストも書いてみてください (`Board` の関数のテストは比較的楽だと思います)

2021-12-16 09:14 UTC, reyu0722 commented on Assets/Scripts/Board/Node/PlotNode.cs
> +        public int Index { get; }
ここなんですけど、他の `IIndexedNode` は `Booard.Nodes` におけるインデックスをそれぞれ持っているので、ここに0とかの数字を入れると多分どこかしらでよくないことが起こります

ただ `IIndexedNode` じゃないと `Path` に入らないので、一旦はこのままでも大丈夫です (どうするか考えるのでちょっと待ってください)

2021-12-26 10:25 UTC, reyu0722 commented on Assets/Scripts/Board/Node/PlotNode.cs
> +        public int Index { get; }
現状ここがIndexedである理由が２つあって
- `Person.cs` で同一かどうかの判断に使っている
- `GetPath` が `IndexedNode` 間での経路探索しかできない

このうち前者はそのまま比較するようにしてもよくて、後者はこのPRで解決するので、`PathNode.Node` を `INode` すると多分いい感じになります

2021-12-29 17:02 UTC, dora1500 commented
一通りpushしました。Path.AddPathNodeが必要なくなるというのがよくわからないのですが、既存の関数で経路探索した道にノードをつなげるいい感じの方法があるってことですか

2021-12-29 19:04 UTC, reyu0722 commented
今はPathを作ってからAddPathNodeで最初と最後をつけているのを、先に最初と最後をつけてからPathを作るようにしたほうがシンプルになりそうという感じです

2022-01-15 19:34 UTC, reyu0722 commented
到着したときに `Person.Arrive()` 内で次のスタート地点がランダムで選ばれているので、そのタイミングで人が瞬間移動しているっぽいです
`getRandomPath` に処理は書かれているのに使われていない状態なので、`Arrive()` からいい感じに呼び出すとよさそうです

2022-03-18 07:32 UTC, merged